### ISSUE TITLE
Creating an action workflow

### ISSUE THREAD

**Issue by philiprbrenan** [lauraminayaa/arrivalTime#2]
Place the following code in file ``.github/workflows/main.yml`` in the folder containing the cloned copy of the Github repository obtained via ``git clone ...``

```
name: Run Python 

on:
  push:

jobs:
  run-python-script:
    runs-on: ubuntu-latest  

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3  # Checkout the code in the repository
-     
    - name: Run Python Script
      run: python read.py the python script
``` 

Then execute these commands:

```
git add *
git commit -maaa
git push
```
to upload the file and launch the action. Look under the ``Actions`` to see the effect.
